version: '2.1'

services:
  postgres:
    image: "postgres:10.5"
    environment:
    - POSTGRES_USER=dbuser
    - POSTGRES_PASSWORD=dbpassword
    - POSTGRES_DB=db1
    ports:
    - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "psql -U dbuser -d db1 -c 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 20
  backend:
    image: "innfactory/iot-manager:1.0"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
    - "9000:9000"
    environment:
    - DATABASE_HOST=postgres
    - DATABASE_USER=dbuser
    - DATABASE_PASSWORD=dbpassword
    - DATABASE_DB=db1