version: 2
jobs:
  test:
    docker:
    - image: innfactory/gcloud-scala-ci:latest
    - image: circleci/postgres:9.6-alpine
      environment:
        POSTGRES_USER: user
        POSTGRES_DB: build
        POSTGRES_PASSWORD: password
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      DATABASE_PORT: 5432
      DATABASE_USER: user
      DATABASE_PASSWORD: password
    steps:
    - checkout
    - run:
        name: "test with sbt"
        command: |
           (
           for i in `seq 1 10`;
                       do
                         nc -z localhost $DATABASE_PORT && echo Success && exit 0
                         echo -n .
                         sleep 1
                       done
                       echo Failed waiting for Postgres && exit 1
           )
    - run: sbt test
  build:
    docker:
    - image: innfactory/gcloud-scala-ci:latest
    - image: circleci/postgres:9.6-alpine
      environment:
        POSTGRES_USER: user
        POSTGRES_DB: build
        POSTGRES_PASSWORD: password
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      DATABASE_PORT: 5432
      DATABASE_USER: user
      DATABASE_PASSWORD: password
    steps:
    - checkout
  deploy:
workflows:
  version: 2
  # build a workflow - test - build - deploy 
  
  # try to optimize the build with caching.